import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'getting-started',
    {
      type: 'category',
      label: 'Foundations',
      items: ['foundations/tokens', 'foundations/colors'],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/overview',
        'components/accordion',
        'components/alert',
        'components/alert-dialog',
        'components/avatar',
        'components/badge',
        'components/breadcrumb',
        'components/button',
        'components/content-switcher',
        'components/context-menu',
        'components/card',
        'components/command',
        'components/date-picker',
        'components/dialog',
        'components/dropdown-menu',
        'components/drawer',
        'components/error-dialogue',
        'components/file-upload',
        'components/hover-card',
        'components/input',
        'components/navigation-menu',
        'components/pagination',
        'components/popover',
        'components/radio-group',
        'components/select',
        'components/progress',
        'components/success-dialogue',
        'components/stepper',
        'components/table',
        'components/tabs',
        'components/textarea',
        'components/toast',
        'components/token-selector',
        'components/tooltip',
        'components/transaction-confirmation',
        'components/switch',
      ],
    },
    {
      type: 'category',
      label: 'Web3 Designs',
      items: [
        'web3-designs/overview',
        'web3-designs/address-display',
        'web3-designs/balance-display',
        'web3-designs/liquidity-pool',
        'web3-designs/staking',
        'web3-designs/swap',
      ],
    },
    {
      type: 'category',
      label: 'Web3 Patterns',
      items: [
        'patterns/overview',
        'patterns/wallet-connect',
        'patterns/transactions/states',
      ],
    },
    {
      type: 'category',
      label: 'Guidelines',
      items: [
        'guidelines/accessibility',
        'guidelines/mobile',
        'guidelines/theming',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/overview',
        'resources/quick-start',
      ],
    },
  ],
};

export default sidebars;
